---
- name: Some generic FE stuff
  hosts: cluster_master
  become: yes
  tasks:

  - name: Set the FQDN
    command: hostname {{inventory_hostname}}

  - name: install numpy
    yum: name=numpy state=present

  - name: Copy a few scripts
    copy: src=alicefiles/{{ item }} dest=/usr/local/bin/{{ item }} mode=755
    with_items:
    - qstatsummary
    - typestat.py
    - typestatsum.py


- name: Some generic stuff
  hosts: all
  become: yes
  tasks:

  - name: Config. yum to use a proxy
    ini_file: dest=/etc/yum.conf section=main option=proxy value="http://192.168.82.60:3128"

  - name: Install the HEP_OSlibs
    yum: name=http://linuxsoft.cern.ch/wlcg/sl6/x86_64/HEP_OSlibs_SL6-1.0.16-0.el6.x86_64.rpm

  - name: Set the timezone; Edit /etc/sysconfig/clock
    lineinfile:
      dest=/etc/sysconfig/clock
      line="ZONE=Europe/Helsinki"
      regexp="ZONE="
      state=present

  - name: Set the timezone; Point /etc/localtime to the correct place
    file:
      path=/etc/localtime
      src=/usr/share/zoneinfo/Europe/Helsinki
      state=link
      force=yes


- name: Create a swap file
  become: yes
  hosts: cluster_slave
  vars:
    swapfile: '/swapfile'
    swapsize: 2G
  tasks:

  - name: Check if the swapfile is already enabled
    command: grep {{ swapfile }} /proc/swaps
    register: swap_found
    ignore_errors: True

  - name: Create swapfile
    command: fallocate -l {{ swapsize }} {{ swapfile }} creates={{ swapfile }}
    when: swap_found|failed

  - name: Format swapfile
    command: mkswap {{ swapfile }}
    when: swap_found|failed

  - name: Set permissions for swapfile
    file: path={{ swapfile }} owner=root group=root mode=0600

  - name: Run swapon
    command: swapon {{ swapfile }}
    when: swap_found|failed

  - name: Put the swapfile into /etc/fstab
    mount: name=swap src={{ swapfile }} fstype=swap opts=sw passno=0 dump=0 state=present


- name: Create the aliprod user on FE and nodes
  hosts: all
  tasks:

  - name: Create the aliprod user
    user: name=aliprod home=/mnt/aliprod
    become: yes

  - name: Create the ssh dir.
    file: dest=~aliprod/.ssh/ mode=700 state=directory
    become: yes
    become_user: aliprod

  - name: Copy public ssh key
    copy: src=~/.ssh/id_rsa.pub  dest=~aliprod/.ssh/authorized_keys mode=600
    become: yes
    become_user: aliprod

  - name: Create dir for aliprod in /mnt/shared_data
    file: dest=/mnt/shared_data/aliprod state=directory owner=aliprod
    become: yes

  - name: check if /mnt/tmp exists (e.g. as a link to somewhere)
    command: test -e /mnt/tmp
    register: mnt_tmp_exists
    ignore_errors: True

  - name: Create /mnt/tmp if it doesn't exist
    file:  path=/mnt/tmp state=directory mode=777
    become: yes
    when: mnt_tmp_exists|failed

  - name: Create a .libnetrc
    copy: src=alicefiles/libnetrc dest=~aliprod/.libnetrc
    become: yes
    become_user: aliprod

    

- name: Configure the AliEn services
  hosts: cluster_master
  become: yes
  become_user: aliprod
  tasks:

  - name: Create the ~aliprod/.alien dir tree
    file: dest=~aliprod/.alien/etc/aliend/ALICE state=directory

  - name: Copy the aliend-startup.conf file
    lineinfile: dest=~aliprod/.alien/etc/aliend/startup.conf line="ALIEN_ORGANISATIONS=ALICE" create=yes

  - name: Copy the ALICE-startup.conf file
    copy: dest=~aliprod/.alien/etc/aliend/ALICE/startup.conf src=alicefiles/ALICE_startup.conf

  - name: Set the ALIEN_DOMAIN env. var.
    lineinfile: line="export ALIEN_DOMAIN=hip-fi" dest=~aliprod/.alien/Environment state=present create=yes

  - name: Create the .globus dir
    file: dest=~aliprod/.globus state=directory mode=700

  - name: Copy the certificate
    copy: src=~/.globus//{{ item.file }} dest=~aliprod/.globus/{{ item.file }} mode={{ item.mode }}
    with_items:
    - { file: userkey.pem, mode: 600 }
    - { file: usercert.pem, mode: 644 }

  - name: Make symlink to .globus
    file: src=~aliprod/.globus dest=~aliprod/.alien/globus state=link

  - name: Set PATH for aliprod
    lineinfile: line="export PATH=$HOME/bin:$PATH:/cvmfs/alice.cern.ch/bin/"  dest=~aliprod/.bashrc  state=present

  - name: Set TMPDIR
    lineinfile: line="export TMPDIR=/mnt/tmp/"  dest=~aliprod/.bashrc  state=present


- name: Some generic node stuff
  hosts: node
  become: yes
  tasks:

  - name: Set up a cron job to clean the filesystem of AliEn files
    copy: src=alicefiles/crondaily dest=/etc/cron.daily/cleanalice mode=755

  - name: Copy the stray process searching script
    copy: src=alicefiles/seek_stray.py dest=/usr/local/bin/seek_stray mode=755

  - name: Add a crontab entry to kill stray processes
    cron: user=aliprod minute="*/15" job="kill `/usr/local/bin/seek_stray ` > /dev/null 2>&1" name="Kill stray processes"


- name:  Install and set up CVMFS
  hosts: cvmfs
  become : yes
  tasks:

  - name: Add the CERNVM repo
    copy: src=alicefiles/cernvm.repo dest=/etc/yum.repos.d/cernvm.repo 

  - name: Import the GPG key of the repo
    get_url: url=http://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM  dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM

  - name: Install CVMFS
    yum: name="{{ item }}" state=latest
    with_items:
    - cvmfs
    - cvmfs-init-scripts

  - name: Configure CVMFS
    template: src=alicefiles/cvmfs-default.j2 dest=/etc/cvmfs/default.local 

  - name: Run cvmfs_config setup
    command: cvmfs_config setup

  - name: Start autofs
    service: name=autofs state=started enabled=yes
