---
- hosts: cluster_master
  name: Cluster master preparation
  sudo: yes
  tasks:

    - include: common/tasks/nfs.yml

    - name: format shared data
      filesystem: fstype=ext4 dev={{ shared_data_device }} opts="-L shared"
      when: shared_data_device is defined

    - name: make sure shared_data_dir exists
      file: path="{{ shared_data_dir }}" state=directory

    - name: mount shared data
      mount: name={{ shared_data_dir }} src='LABEL=shared' state=mounted opts=defaults fstype=ext4
      when: shared_data_device is defined
      notify:
        - restart nfsd
        - restart nfs-kernel-server

    - name: export shared data
      nfsexport: path={{ shared_data_dir }} dest=/etc/exports clients="{{ groups.cluster_slave }}"
                 options=rw,no_root_squash,async
      notify:
        - restart nfsd
        - restart nfs-kernel-server

    - name: export home
      nfsexport: path=/home dest=/etc/exports clients="{{ groups.cluster_slave }}" options=rw,no_root_squash,sync
      notify:
        - restart nfsd
        - restart nfs-kernel-server

    - name: install pdsh
      yum: name=pdsh state=present
      when: is_centos

    - name: install pdsh
      apt: name=pdsh state=present
      when: is_debian_or_ubuntu

    - name: set pdsh default transport to ssh
      lineinfile: name=/etc/pdsh/rcmd_default create=yes line='ssh' state=present

  handlers:
    - include: common/handlers/main.yml

- hosts: cluster_master:cluster_slave
  name: Common cluster preparation
  sudo: yes
  tasks:
    - include: common/tasks/iptables.yml trusted_hosts="{{ groups.all }}" default_accept=1

    - name: make sure local_data_dir exists
      file: path="{{ local_data_dir }}" state=directory

    - name: format local data
      filesystem: fstype=ext4 dev={{ local_data_device }} opts="-L data -m 0"
      when: local_data_device is defined

    - name: mount local data
      action: mount name={{ local_data_dir }} src=LABEL=data fstype=auto opts=rw,nofail state=mounted
      when: local_data_device is defined

  handlers:
    - include: common/handlers/main.yml

- hosts: cluster_slave
  name: Cluster slave preparation
  sudo: yes
  tasks:
    - include: common/tasks/nfs-clients.yml nfsserver="{{ groups.cluster_master[0] }}" nfspath=/home nfsmount=/home
    - include: common/tasks/nfs-clients.yml nfsserver="{{ groups.cluster_master[0] }}" nfspath={{ shared_data_dir }}
               nfsmount={{ shared_data_dir }}
