---
- name: Common setup
  hosts: common
  become: yes
  tasks: 
    #- include: common/tasks/deb.yml
    - include: common/tasks/epel_repo.yml
    - include: common/tasks/packages.yml
    - include: common/tasks/hosts.yml hosts="{{ groups.all }}"
    - include: common/tasks/hostname.yml
    - include: common/tasks/ssh_host_based_authentication.yml hosts="{{ groups.all }}"

  handlers:
    - include: common/handlers/main.yml
