---
- name: Common configuration
  hosts: ge_master:ge_slave
  sudo: yes
  tasks:
    - include: common/tasks/packages.yml
    - include: common/tasks/iptables.yml trusted_hosts="{{ groups.all }}"
  handlers:
    - include: common/handlers/main.yml
    - include: gridengine/handlers/main.yml

- name: GridEngine masternode play
  hosts: ge_master
  sudo: yes
  tasks: 
    - include: gridengine/tasks/frontend.yml
    - action: shell bash -lc 'qconf -mattr queue slots 16 all.q'
    - include: common/tasks/nfs.yml
  handlers:
    - include: common/handlers/main.yml
    - include: gridengine/handlers/main.yml

- name: GridEngine worker nodes play
  hosts: ge_slave
  sudo: yes
  tasks: 
    - include: common/tasks/nfs-clients.yml nfsserver="{{ groups.ge_master[0] }}" nfspath=/usr/share/gridengine/default/common nfsmount=/usr/share/gridengine/default/common
      when: is_centos
    - include: gridengine/tasks/nodes.yml
  handlers:
    - include: common/handlers/main.yml
    - include: gridengine/handlers/main.yml

- name: Config GridEngine
  hosts: ge_master
  become: yes
  environment:
    SGE_ROOT: /usr/share/gridengine
  tasks:

  - name: Set some ALICE friendly values for the queue all.q
    command: qconf -mattr queue {{ item.var }} {{ item.val }} all.q
    with_items:
      - { var: 'h_rt', val: '172800' }
      - { var: 'h_vmem', val: '10737418240' }
      - { var: 'shell', val: '/bin/bash' }
      - { var: 'tmpdir', val: '/mnt/tmp' }

