---
- name: Common configuration
  hosts: ge_master:ge_slave
  sudo: yes
  roles:
    - slurm-common

- name: GridEngine masternode play
  hosts: ge_master
  sudo: yes
  roles:
    - slurm-fe

- name: GridEngine worker nodes play
  hosts: ge_slave
  sudo: yes
  roles:
    - slurm-wn
