---
- name: Prepare stuff on localhost
  hosts: localhost
  connection: local
  roles:
    - slurm-local

- name: Common prerequisites
  hosts: frontend:node
  roles:
    - slurm-pre-common

- name: Frontend preparations
  hosts: frontend
  roles:
    - slurm-compile

- name: Common configuration
  hosts: frontend:node
  roles:
    - slurm-common

- name: Slurm masternode play
  hosts: frontend
  roles:
    - slurm-fe

- name: Slurm worker nodes play
  hosts: node
  roles:
    - slurm-wn
