---
- name: Common configuration
  hosts: frontend:node
  become: yes
  roles:
    - slurm-common

- name: GridEngine masternode play
  hosts: frontend
  become: yes
  roles:
    - slurm-fe

- name: GridEngine worker nodes play
  hosts: node
  become: yes
  roles:
    - slurm-wn
