---
- name: Prepare stuff on localhost
  hosts: localhost
  connection: local
  roles:
    - munge-prep

- name: Common configuration
  hosts: frontend:node
  roles:
    - slurm-compile
    - slurm-common

- name: Slurm masternode play
  hosts: frontend
  roles:
    - slurm-fe

- name: Slurm worker nodes play
  hosts: node
  roles:
    - slurm-wn
