---
- hosts: spark_master:spark_slave
  name: Install Spark
  become: yes
  vars:
    spark_version: "1.3.1"
    spark_flavor: "hadoop1"
#    tar_url: "http://www.eu.apache.org/dist/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-{{ spark_flavor }}.tgz"
    tar_url: "http://www.nic.funet.fi/pub/mirrors/apache.org/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-{{ spark_flavor }}.tgz"
    spark_confdir: "/opt/spark/conf"
    spark_localdir: "{{ local_data_dir }}"
  tasks: 
    - include: spark/tasks/install.yml
    - include: spark/tasks/conf.yml

    - name: Start Spark master and slaves on master
      command: /opt/spark/sbin/start-all.sh
      when: inventory_hostname in groups.spark_master
