---
- name: Install MariaDB
  yum:
    name: ['mariadb-server', 'mariadb-devel']
    state: installed
  become: yes

- name: Start & enable the mariadb service
  become: yes
  service:
    name: mariadb
    enabled: yes
    state: started
