---
- name: Install MariaDB
  become: yes
  yum:
    name: ['mariadb-server', 'mariadb-devel']
    state: installed

- name: Start & enable the mariadb service
  become: yes
  service:
    name: mariadb
    enabled: yes
    state: started

#- name: Set MySQL root Password
#  become: True
#  mysql_user: 
#    name: root
#    password: "{{ mariadb_pw }}"
#    check_implicit_admin: yes
#    login_unix_socket: /var/lib/mysql/mysql.sock
#    login_user: root
#    state: present
