---
- name: Install prerequisities
  become: yes
  yum:
    state: present
    name:
    - pyOpenSSL
    - python-dateutil

- name: Download & unpack bart
  unarchive:
    src: http://www.sgas.se/releases/sgas-bart-{{ bart_version }}.tar.gz
    remote_src: True
    dest: ~/
    creates: ~/sgas-bart-{{ bart_version }}
  when: bart_version != "git"

- name: Clone the BART git repo
  git:
    #repo: git@github.com:sgas/bart.git
    repo: https://github.com/sgas/bart.git
    dest: sgas-bart-git
    accept_hostkey: yes
  when: bart_version == "git"
  ignore_errors: True

- name: Install bart
  become: yes
  command: python setup.py install
  args:
    chdir: ~{{ remoteuser }}/sgas-bart-{{ bart_version }}
    creates: /usr/local/bin/bart-logger


- name: Copy bart.conf
  become: yes
  template:
    src: bart.conf.j2
    dest: /etc/bart/bart.conf

#- name: Create log files with correct ownership
#  become: yes
#  ansible.builtin.file:
#    path: "/var/log/{{ item }}"
#    owner: "{{ remoteuser }}"
#    state: touch
#  with_items:
#    - bart-logger.log
#    - bart-registration.log
 
- name: Create a spool dir
  become: yes
  ansible.builtin.file:
    path: "/var/spool/bart"
    #owner: "{{ remoteuser }}"
    state: directory

- name: Set up a cron job
  become: yes
  ansible.builtin.cron:
    cron_file: bart
    job: "bart-logger && python3 /usr/local/bin/bart-registrant"
    minute: "15"
    name: "Report usage to SGAS"
    user: root
