#!/bin/bash

squeue -o "%.18i %.9P %.8j %.8u %.2t %.10M %.6C %R" | awk '$5 == "R"{n[$8]+=$7;ncores += $7}END{for (m in n) { print m, n[m]; nnodes++} print "b---------------"; print "Total cores: " ncores; print "Total nodes: " nnodes}' | sort 
