---
# Key used with the admin node
adminkey: eriknew

# Flavor of the Bastion/admin node
admin_flavor:  standard.tiny

# Image (OS) if the admin node
admin_image: CentOS-7

# Key used with the cluster
clusterkey: eriknew

# Flavor of the cluster frontend
frontend_flavor: standard.tiny
frontend_image: CentOS-7

# Flavor of the cluster worker nodes
wn_flavor: standard.tiny
#wn_flavor: standard.small
wn_image: CentOS-7

# Worker node local disk
wn_local_disk: 12

network: project_2001054


openstackrc: ~/.config/project_2001054-openrc.sh
