---
- name: Add cluster hosts to local /etc/hosts
  sudo: yes
  action: lineinfile
          create=yes
          state=present
          dest=/etc/hosts
          regexp="{{ item }}"
          line="{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}"
  when: hostvars[item]['ansible_ssh_host'] is defined
  with_items: groups.all

- name: Add frontend FQDN to /etc/hosts
  replace: regexp="^([0-9.]* {{groups['frontend'][0]}}).*$" replace="{{groups['frontend'][0]}}.hip.fi \1" dest=/etc/hosts

