---
# This task is used to mount a filesystem via NFS.
# 
# Variables you need to define:
# nfsserver:   the nfs server to mount from
# nfspath:     the remote filesystem to mount from the nfs server
# nfsmount:    the directory where you want to mount the filesystem.
# nfsoptions:  options to use when mounting the filesystem. If not
#              defined, `rw,sync` will be used.
#
# Please note that the task will check if the {{nfsmount}} directory
# exists and create it otherwise.
#

- name: install nfs client (CentOS)
  yum: name=nfs-utils state=present
  tags:
    - nfs

- name: Ensure rpcbind is running (CentOS)
  action: service name=rpcbind state=started enabled=yes

- name: Ensure {{nfsmount}} directory exists
  file:
    path: "{{nfsmount}}"
    state: directory
  tags: 
    - nfs

- name: Set nfsopts
  shell: if [ -z "$nfsoptions" ]; then  echo rw,sync,nfsvers=4; else echo $nfsoptions; fi
  register: _nfsopts
  become: false
  connection: local
  tags:
    - nfs


# If this fails, restarting the nfs-server on the front end often helps
- name: configure /etc/fstab on clients
  mount:
    name: "{{nfsmount}}"
    src: "{{nfsserver}}:{{nfspath}}"
    fstype: nfs
    opts: "{{_nfsopts.stdout}}"
    state: mounted
  tags:
    - nfs
