---
- name: Config. yum to use a proxy
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: proxy
    value: "http://{{ lookup('pipe', 'my_ip') }}:3128"

- name: update the system (CentOS)
  yum: name=* state=latest

- name: install acpid for soft reboots (CentOS)
  yum: name=acpid state=present

- name: configure and start acpid service
  service: name=acpid state=started enabled=true

- name: Install chrony
  yum:
    name: chrony

- name: Set up NTP
  service: name=chronyd enabled=yes state=started

- name: install misc auxiliary packages (CentOS)
  yum:
    state: present
    name:
    - tree
    - wget
    - bash-completion
    - dstat
    - nc
    - mlocate
    - screen
    - tmpwatch
    - vim-X11
    - vim-enhanced
    - openldap-clients
