---
- name: update the system (CentOS)
  yum: name=* state=latest
  when: is_centos

- name: install acpid for soft reboots (CentOS)
  yum: name=acpid state=present
  when: is_centos

- name: configure and start acpid service
  service: name=acpid state=started enabled=true

- name: Set up NTP
  service: name=ntpd enabled=yes state=started

- name: install misc auxiliary packages (CentOS)
  yum: name="{{ item }}" state=present
  with_items:
  - tree
  - wget
  - bash-completion
  - dstat
  - nc
  - mlocate
  - screen
  when: is_centos
