---
- name: Install GridEngine RPM packages
  yum: name={{item}} state=latest
  when: is_centos
  with_items:
    - gridengine-execd

- name: ensure execd daemon is running
  action: service name=sge_execd state=running
  when: is_centos
