---
# https://github.com/ansible/ansible-modules-core/issues/1170
- name: restart sshd
  action: service name=sshd state=restarted

- name: restart iptables
  action: service name=iptables state=restarted

- name: reload exports
  shell: exportfs -r

- name: ensure nfs service is running
  service: name=nfs-server state=started

- name: restart nfsd
  service: name=nfs-server state=restarted

- name: kill-HUP sshd
  shell: pkill -HUP sbin/sshd

- name: reboot
  reboot:
