---
# https://github.com/ansible/ansible-modules-core/issues/1170
- name: restart sshd
  action: service name=sshd state=restarted
  when: is_centos

- name: restart iptables
  action: service name=iptables state=restarted
  when: is_centos

- name: reload exports
  shell: exportfs -r

- name: ensure nfs service is running
  service: name=nfs state=started
  when: is_centos

- name: restart nfsd
  service: name=nfs state=restarted
  when: is_centos

- name: kill-HUP sshd
  shell: pkill -HUP sbin/sshd

- name: reboot
  command: /sbin/reboot
