---
- name: Create /var/spool/slurmctld
  become: yes
  file:
    path: /var/spool/slurmctld
    owner: slurm
    group: slurm
    mode: 0755
    state: directory

- name: Touch a bunch of log files
  become: yes
  file:
    path: "/var/log/{{ item }}"
    owner: slurm
    group: slurm
    state: touch
  with_items:
  - slurmctld.log
  - slurmdbd.log
  - slurm_jobacct.log
  - slurm_jobcomp.log

- name: Create a slurm MariaDB user
  become: yes
  community.mysql.mysql_user:  # Might require `ansible-galaxy collection install community.mysql`
    login_user: root
    login_password: "{{ mariadb_pw }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: slurm
    password: '{{ slurm_dbpw }}'
    priv: '*.*:ALL'
    state: present

- name: Copy a slurmdbd.conf file
  become: yes
  template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: 0600

- name: Enable & start slurmdbd
  become: yes
  service: 
    name: slurmdbd
    enabled: yes
    state: restarted

- name: Enable & start slurmctld
  become: yes
  service: 
    name: slurmctld
    enabled: yes
    state: restarted
