---
- name: Create /var/spool/slurmctld
  become: yes
  file:
    path: /var/spool/slurmctld
    owner: slurm
    group: slurm
    mode: 0755
    state: directory

- name: Touch a bunch of log files
  become: yes
  file:
    path: "/var/log/{{ item }}"
    owner: slurm
    group: slurm
    state: touch
  with_items:
  - slurmctld.log
  - slurm_jobacct.log
  - slurm_jobcomp.log

- name: Enable & start slurmctld
  become: yes
  service: 
    name: slurmctld
    enabled: yes
    state: restarted
