---
- name: Install dependencies
  become: yes
  yum:
    state: installed
    name:
    - openssl
#    - openssl-devel
    - pam-devel
    - numactl
#    - numactl-devel
    - hwloc
#    - hwloc-devel
    - lua
#    - lua-devel
#    - readline-devel
#    - rrdtool-devel
#    - ncurses-devel
    - man2html
    - libibmad
    - libibumad
#    - rpm-build
#    - perl-ExtUtils-MakeMaker

#- name: blah
#  debug:
#    var: hostvars

- name: Find Slurm RPMs
  shell: "ls {{ slurm_rpms }}/slurm*.x86_64.rpm"
  register: ls_rpms

- name: Install Slurm RPMs
  become: yes
  yum:
    name: "{{ ls_rpms.stdout_lines }}"
    state: present

- name: create a slurm user
  become: yes
  user:
    name: slurm
    createhome: no

#- name: debug
#  debug:
#    var: hostvars

- name: Copy conf files
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/slurm/{{ item }}"
  with_items:
  - slurm.conf

- name: Edit systemd/slurm*.service
  become: yes
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
    regexp: "PIDFile=.*"
  with_items:
  - { path: /usr/lib/systemd/system/slurmd.service, line: "PIDFile=/var/run/slurm/slurmd.pid" }
  - { path: /usr/lib/systemd/system/slurmctld.service, line: "PIDFile=/var/run/slurm/slurmctld.pid" }


- name: Create a few dirs /var/run/slurm/
  become: yes
  file:
    name: "{{ item }}"
    state: directory
    owner: slurm
    group: slurm
  with_items:
  - /var/run/slurm/
  - /var/log/slurm/
