---
#
# Master playbook for generic cluster on Pouta.
#
# Ansible playbooks based on ElastiCluster
# https://github.com/gc3-uzh-ch/elasticluster
# 

# common stuff for all groups
- include: roles/common.yml

# common setup for master - slave
- include: roles/cluster.yml

# ALICE stuff (has be done before the gridengine stuff)
- include: roles/alicefy.yml

# ganglia for monitoring
- include: roles/ganglia.yml

# SLURM for batch prosessing
- include: roles/slurm.yml

# Hadoop/HDFS for map reduce and distributed filesystem
- include: roles/hadoop.yml

# Spark for next gen map reduce, runs on HDFS
- include: roles/spark.yml
