---
#
# Master playbook for generic cluster on Pouta.
#
# Ansible playbooks based on ElastiCluster
# https://github.com/gc3-uzh-ch/elasticluster
# 

# common stuff for all groups
- import_playbook: roles/common.yml

# common setup for master - slave
- import_playbook: roles/cluster.yml

# ALICE stuff (has be done before the gridengine stuff)
- import_playbook: roles/alicefy.yml

# SLURM for batch prosessing
- import_playbook: roles/slurm.yml

# BaRT, for SGAS reporting
- import_playbook: roles/bart.yml
