---
- name: Install dependencies
  become: yes
  yum:
    state: installed
    name:
    - rpm-build
    - readline-devel
    - perl-ExtUtils-MakeMaker
    - pam-devel
#    - openssl
#    - openssl-devel
#    - numactl
#    - numactl-devel
#    - hwloc
#    - hwloc-devel
#    - lua
#    - lua-devel
#    - rrdtool-devel
#    - ncurses-devel
#    - man2html
#    - libibmad
#    - libibumad
#    - gtk+
#    - gtk+-devel
#    - hdf5
#    - hdf5-devel
#    - lz4
#    - lz4-devel
#    - hwloc
#    - hwloc-devel


- name: Make sure "{{ slurm_rpmbuild }}" exists
  file:
    name: "{{ slurm_rpmbuild }}"
    state: directory

- name: Download slurm
  get_url: 
    url: "https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2"
    dest: "{{ slurm_build_root }}/slurm-{{ slurm_version }}.tar.bz2"

- name: Build RPMs
  shell: "HOME={{ slurm_build_root }} rpmbuild -ta {{ slurm_build_root }}/slurm-{{ slurm_version }}.tar.bz2 > {{ slurm_build_root }}/slurm-build.log 2>&1"
  args:
    creates: "{{ slurm_rpmbuild }}/RPMS/x86_64/slurm*.x86_64.rpm"

- name: Make dir for the RPMs
  file:
    path: "{{ slurm_rpms }}"
    state: directory

- name: Copy the RPMs to their destination
  shell: "cp {{ slurm_rpmbuild }}/RPMS/x86_64/slurm*.x86_64.rpm {{ slurm_rpms }}/"
  args:
    creates: "{{ slurm_rpms }}/slurm*.x86_64.rpm"
