---
- name: Install dependencies
  become: yes
  yum:
    state: installed
    name:
    - rpm-build
    - readline-devel
    - pam-devel
    - perl-ExtUtils-MakeMaker
    - munge-devel
    - python3

- name: Make sure "{{ slurm_rpmbuild }}" exists
  file:
    name: "{{ slurm_rpmbuild }}"
    state: directory

- name: Download slurm
  get_url: 
    url: "https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2"
    dest: "{{ slurm_build_root }}/slurm-{{ slurm_version }}.tar.bz2"

- name: Build RPMs
  shell: "HOME={{ slurm_build_root }} rpmbuild -ta {{ slurm_build_root }}/slurm-{{ slurm_version }}.tar.bz2 > {{ slurm_build_root }}/slurm-build.log 2>&1"
  args:
    creates: "{{ slurm_rpmbuild }}/RPMS/x86_64/slurm*.x86_64.rpm"

- name: Make dir for the RPMs
  become: yes
  file:
    path: "{{ slurm_rpms }}"
    state: directory
    mode: 0755
    owner: "{{ remoteuser }}"

- name: Copy the RPMs to their destination
  shell: "cp {{ slurm_rpmbuild }}/RPMS/x86_64/slurm*.x86_64.rpm {{ slurm_rpms }}/"
  args:
    creates: "{{ slurm_rpms }}/slurm*.x86_64.rpm"
