---
- name: Some generic stuff
  hosts: all
  tasks:

  - name: Install some stuff
    become: yes
    yum:
      state: latest
      name: 
        - vim-X11
        - xorg-x11-xauth
        - dejavu-sans-mono-fonts
        - PackageKit-gtk3-module
        - libcanberra-gtk2
        - nc
        - screen
        - bash-completion
        - yum-plugin-priorities
        - git
        - mlocate

  - name: Set the timezone
    become: yes
    command: timedatectl set-timezone Europe/Helsinki
