---
- name: Some generic stuff
  hosts: all
  tasks:

  - name: Install some stuff
    become: yes
    yum:
      state: latest
      name: 
        - vim-X11
        - xorg-x11-xauth
        - dejavu-sans-mono-fonts
        - PackageKit-gtk3-module
        - libcanberra-gtk2
        - nc
        - bash-completion
        - git
        - mlocate

  - name: Set the timezone
    become: yes
    command: timedatectl set-timezone Europe/Helsinki

  - name: Create a .ssh dir
    file:
      path: ~/.ssh
      state: directory
      mode: 0700

  - name: Populate the .ssh dir with an empty pub file
    file:
      path: ~/.ssh/empty.pub
      state: touch
      mode: 0644
