---
- name: Install the ALICE version of 'pouta-virtualcluster'
  hosts: all
  tasks:
  

  - name: Install EPEL
    become: yes
    ansible.builtin.yum:
      name: epel-release

  - name: Install some stuff
    become: yes
    yum:
      state: latest
      name:
        - openssh-clients
        - ansible
        - python3-pip

  - name: Install the Openstack client and other python packages
    ansible.builtin.pip:
      name: 
        - python-openstackclient
        - python-keystoneclient
        - python-novaclient
        - python-cinderclient
        - python-neutronclient
        - python-glanceclient
        #- python-yaml
        - yaml-1.3

  - name: Copy the openrc.sh file
    copy: 
      src: "{{ openstackrc }}"
      dest: ~/openrc.sh
      mode: 0600
      owner: "{{ remoteuser }}"
    
  - name: Create a .globus dir
    file: dest=~/.globus state=directory

  - name: copy the certificate
    copy:
      src=templates/{{ item }}
      dest=~/.globus/{{ item }}
      mode=600
      owner={{ remoteuser }}
    with_items:
      - usercert.pem
      - userkey.pem

#  - name: Copy .gitconfig
#    copy: src=~/.gitconfig dest=~/.gitconfig

  - name: Clone the pouta-virtualcluster git repo
    ansible.builtin.git:
      repo: https://github.com/edelmann/pouta-virtualcluster.git
      dest: "~{{ remoteuser }}-user/pouta-virtualcluster"
      update: no

  - name: Create a ~/bin
    file: dest=~/bin state=directory

  - name: Make a few links
    file: dest={{ item.dest }} src={{ item.src }} state=link
    with_items:
    - { dest: ~/bin/poutacluster, src: ~/pouta-virtualcluster/python/poutacluster.py }
    - { dest: ~/ansible, src: ~/pouta-virtualcluster/ansible }
    - { dest: ~/.ansible.cfg, src: ~/pouta-virtualcluster/ansible/cfg/ansible-centos6.cfg }

  - name: Create a alice-cluster dir
    file: dest=~/alice-cluster state=directory

  #- name: blah
    #debug:
      #var: hostvars

  - name: Copy the cluster.yml file
    template:
      src: cluster.yml.j2
      dest: ~/alice-cluster/cluster.yml

  - name: Create a group_vars dir
    file:
      dest: ~/alice-cluster/group_vars
      state: directory

  - name: Copy a sample group_vars/all.yml file
    tamplate:
      src: all.yml.j2
      dest:  ~/alice-cluster/group_vars/all.yml
      mode: 0600

  - name: Copy my_ip script
    copy:
      src: templates/my_ip
      dest: ~/bin/my_ip
      mode: 0755
