---
- name: Install munge
  yum:
    name: ['munge', 'munge-libs', 'munge-devel']
    state: installed
  become: yes

- name: Make sure /etc/munge exists locally
  become: yes
  file:
      name: /etc/munge
      state: directory
      mode: 0500
      owner: "{{ remoteuser }}"
  delegate_to: localhost

- name: Create the key
  become: yes
  shell: |
    dd if=/dev/urandom bs=1 count=1024 >/etc/munge/munge.key
    chmod 0400 /etc/munge/munge.key
    chown {{ remoteuser }} /etc/munge/munge.key
  args:
    creates: /etc/munge/munge.key
  delegate_to: localhost

- name: Copy the key
  become: yes
  copy:
    src: /etc/munge/munge.key
    dest: /etc/munge/munge.key 
    mode: 0400
    owner: munge
    group: munge

- name: Enable the munge daemon
  become: yes
  service:
    name: munge
    enabled: yes
    state: started
